version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Version Check
          command: |
            npm -v
      - node/install-packages:
          app-dir: ~/project/React-Website
          cache-path: ~/project/React-Website/node_modules
          override-ci-command: npm i
          pkg-manager: npm
      - run:
          name: Run Tests
          command: |
            echo "Skip tests"
      - run:
          name: Build App
          command: |
            cd ~/project/React-Website
            echo 'export CI=false' >> $BASH_ENV
            source $BASH_ENV
            echo $CI
            npm run build
      - persist_to_workspace:
          root: ~/project/
          paths:
          - .
  deploy-website:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/project/
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run:
          name: skip key authentication message
          command: |         
            echo "PubkeyAuthentication yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - run: 
          name: Install rsync
          cache-path: ~/project/
          command: |
            sudo apt install rsync
      - run: 
          name: Deploy Website via SSH
          command: |
            cd React-Website
            ls
            rsync -rv build/ $SSH_USER@$SSH_HOST:public_html/
 
workflows:
  deploy-website:
    jobs:
      - test-node
      - deploy-website:
          requires:
            - test-node
          filters:
            branches:
              only: master