version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-node:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: Version Check
          command: |
            npm -v
      - run:
          name: Install Packages
          app-dir: ~/project/React-Website
          command: |
            npm install
      - run:
          name: Run Tests
          command: |
            echo "Skip tests"
      - run:
          name: Build App
          command: |
            cd ~/project/React-Website
            npm run build
      - persist_to_workspace:
          root: ~/project/
          paths:
          - .
  deploy-website:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/project/
    steps:
      - run: 
          name: Deploy Website via SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "touch test.txt"

 
workflows:
  deploy-website:
    jobs:
      - test-node
      - deploy-website:
          requires:
            - test-node
          filters:
            branches:
              only: master