version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Version Check
          command: |
            npm -v
      - node/install-packages:
          app-dir: ~/project/React-Website
          cache-path: ~/project/React-Website/node_modules
          override-ci-command: npm i
          pkg-manager: npm
      - run:
          name: Run Tests
          command: |
            echo "Skip tests"
      - run:
          name: Build App
          command: |
            cd ~/project/React-Website
            echo 'export CI=false' >> $BASH_ENV
            source $BASH_ENV
            echo $CI
            npm run build
      - persist_to_workspace:
          root: ~/project/
          paths:
          - .
  deploy-website:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/project/
    steps:
      - run:
          name: skip key authentication message
          command: |
            sudo cat ~/.ssh/config
            sudo chmod 400 ~/.ssh/config            
            echo "PubkeyAuthentication yes" >> ~/.ssh/config
            echo "StrictHostKeyChecking no" >> ~/.ssh/config
            service sshd restart
      - add_ssh_keys:
          fingerprints:
            - "ec:75:b2:b8:de:41:b5:84:72:fb:f4:40:c3:71:72:4e"
      - run: 
          name: Deploy Website via SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "touch test.txt"

 
workflows:
  deploy-website:
    jobs:
      - test-node
      - deploy-website:
          requires:
            - test-node
          filters:
            branches:
              only: master